package com.example.designflair.model

data class Designs(val list: ArrayList<String> = arrayListOf(
    "Christmas",
    "Modern",
    "Neutral",
    "Monochromatic",
    "Complementary",
    "Cyberpunk",
    "Analogous",
    "Warm",
    "Cool",
    "Pastel",
    "Black and white",
    "Earthy",
    "Vintage",
    "Minimalist",
    "Scandinavian",
    "Bohemian",
    "High-Contrast",
    "Bright",
    "Ocean-inspired",
    "Rustic",
    "Tropical",
    "Bold",
    "Jewel-toned",
    "Art Deco",
    "Mediterranean",
    "Traditional",
    "Beachy",
    "Spanish",
    "Swedish",
    "Boho",
    "Victorian gothic",
    "Organic modern",
    "Dark academia",
    "Modern rustic",
    "Art deco modern",
    "Industrial chic",
    "Industrial rustic",
    "Rustic",
    "Industrial",
    "Eclectic",
    "Victorian",
    "Luxury",
    "Gothic",
    "Moroccan",
    "French",
    "Mexican"
))
