package com.example.designflair.model

data class Rooms(val list: ArrayList<String> = arrayListOf(
    "Living Room",
    "Dining Room",
    "Gaming Room",
    "Bedroom",
    "Bathroom",
    "Office",
    "Kitchen",
    "Guest Room",
    "Laundry Room",
    "Home Theater",
    "Playroom",
    "Music Room",
    "Exercise Room",
    "Library",
    "Sunroom",
    "Mudroom",
    "Attic",
    "Basement",
    "Pantry",
    "Wine Cellar",
    "Garage",
    "Outdoor Living Space",
    "Pool Room",
    "Study Room",
    "Home Office",
    "House Exterior",
    "Outdoor Pool Area",
    "Outdoor Patio",
    "Outdoor Garden",
    "Meeting Room",
    "Workshop",
    "Fitness Gym",
    "Coffee Shop",
    "Clothing Store",
    "Walk-in Closet",
    "Toilet",
    "Restaurant",
    "Coworking Space",
    "Hotel Lobby",
    "Hotel Room",
    "Hotel Bathroom",
    "Exhibition Space",
    "Onsen",
    "Drop Zone"
))
